# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/teste

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:

  ApplicationStop:
    - location: config/scripts/app_stop.sh
      timeout: 300
      runas: ubuntu
  
  BeforeInstall:
    - location: config/scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: config/scripts/aftet_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: config/scripts/app_start.sh
      timeout: 300
      runas: ubuntu