version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/api
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: config/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: config/scripts/aftet_install.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: config/scripts/app_start.sh
      timeout: 300
      runas: root
