# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux

files:
  - source: /
    destination: /opt/app/observador-app-server

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:

  ApplicationStop:
    - location: /config/scripts/app_stop.sh
      timeout: 300
      runas: root
  
  BeforeInstall:
    - location: config/scripts/before_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: config/scripts/app_start.sh
      timeout: 300
      runas: root