version : 0.2
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling

  post_build:
    commands:
      - echo Build completed on `date`
    
artifacts:
  files:
    - package.json
    - appspec.yml
    - config/scripts/**
    - controllers/**
    - models/**/*
    - routes/**
  
